### ISSUE TITLE
breaking change in semantic-release@16

### ISSUE THREAD

**Issue by tomas-mechura** [bahmutov/condition-circle#22]
There is breaking change in semantic-release@16 which resulted in failing `verifyConditions` step with this plugin, as `release.branch` has been renamed to `release.branches`.

If you not specify release branch in package.json. The semantic release was adding default 'master' prior to version 16. Now it is adding branches, which condition-circle is not counting with.

This result to error:
```
AggregateError: 
SemanticReleaseError: CircleCI using 'master' not configured publish branch (undefined)
  at conditionCircle (node_modules/condition-circle/src/condition-circle.js:31:11)
```

**Comment by khamiltonuk** [comment]
Looks like this has been fixed, I would recommend closing this issue
https://github.com/semantic-release/semantic-release/releases/tag/v16.0.4

**Comment by frontendphil** [comment]
I've created this PR https://github.com/bahmutov/condition-circle/pull/23 to help fix this.

**Comment by allens01** [comment]
This looks like it is still an issue, can the PR #23 be merged and an update published?
